#include "../include_cheat.h"

c_hook* hooks::client = nullptr;
c_hook* hooks::clientmode = nullptr;
c_hook* hooks::engine = nullptr;
c_hook* hooks::modelrender = nullptr;
c_hook* hooks::viewrender = nullptr;
c_hook* hooks::enginetrace = nullptr;
c_hook* hooks::renderview = nullptr;
c_hook* hooks::vpanel = nullptr;
c_hook* hooks::device = nullptr;
c_hook* hooks::fire_bullets = nullptr;
c_hook* hooks::engine_sound = nullptr;
c_hook* hooks::surface = nullptr;
c_hook* hooks::death_notice = nullptr;
c_bphook* hooks::clientstateplus8 = nullptr;
c_bphook* hooks::ccsplayer = nullptr;
c_bphook* hooks::cbasesplayeranimstate = nullptr;
c_bphook* hooks::ccsplayerrenderable = nullptr;
c_hook* hooks::net_channel = nullptr;
c_hook* hooks::debug_spread_show = nullptr;
c_hook* hooks::net_showfragments = nullptr;
c_hook* hooks::sv_cheats = nullptr;

recv_prop_hook* hooks::smoke_prop = nullptr;
recv_prop_hook* hooks::eye0_prop = nullptr;
recv_prop_hook* hooks::eye1_prop = nullptr;
recv_prop_hook* hooks::lby_prop = nullptr;
recv_prop_hook* hooks::sequence_prop = nullptr;
recv_prop_hook* hooks::rotation_prop = nullptr;

WNDPROC hooks::orig_wnd_proc;
hooks::create_move_fn hooks::orig_create_move;
hooks::frame_stage_notify_fn hooks::orig_frame_stage_notify;
hooks::draw_model_execute_fn hooks::orig_draw_model_execute;
hooks::render_view_fn hooks::orig_render_view;
hooks::is_box_visible_fn hooks::orig_is_box_visible;
hooks::scene_end_fn hooks::orig_scene_end;
hooks::get_int_fn hooks::orig_debug_spread_show_get_int;;
hooks::get_bool_fn hooks::orig_sv_cheats_get_bool;
hooks::get_bool_fn hooks::orig_net_showfragments_get_bool;
hooks::do_post_screen_space_effects_fn hooks::orig_do_post_screen_space_effects;
hooks::present_fn hooks::orig_present;
hooks::reset_fn hooks::orig_reset;
hooks::send_datagram_fn hooks::orig_send_datagram;
hooks::send_net_msg_fn hooks::orig_send_net_msg;
hooks::is_hltv_fn hooks::orig_is_hltv;
hooks::paint_traverse_fn hooks::orig_paint_traverse;
hooks::override_view_fn hooks::orig_override_view;
hooks::emit_sound_fn hooks::orig_emit_sound;
hooks::temp_entities_fn hooks::orig_temp_entities;
hooks::fire_bullets_postdataupdate_fn hooks::orig_fire_bullets_postdataupdate;
hooks::do_extra_bone_processing_fn hooks::orig_do_extra_bone_processing;
hooks::play_sound_fn hooks::orig_play_sound;
hooks::is_connected_fn hooks::orig_is_connected;
hooks::push_notice_call_fn hooks::orig_process_input;
hooks::eye_angles_fn hooks::orig_eye_angles;
hooks::standard_blending_rules_fn hooks::orig_standard_blending_rules;
hooks::do_animation_event_fn hooks::orig_do_animation_event;
hooks::maintain_sequence_transitions_fn hooks::orig_maintain_sequence_transitions;
hooks::fire_event_fn hooks::orig_fire_event;
hooks::trace_ray_fn hooks::orig_trace_ray;
RecvVarProxyFn hooks::orig_smoke_effect;
RecvVarProxyFn hooks::orig_m_angEyeAngles0Proxy;
RecvVarProxyFn hooks::orig_m_angEyeAngles1Proxy;
RecvVarProxyFn hooks::orig_m_flLowerBodyYawTargetProxy;
RecvVarProxyFn hooks::orig_sequence;
RecvVarProxyFn hooks::orig_m_angRotationProxy;
